# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-issuer-secret
  namespace: kube-system
data:
  CLOUDFLARE_API_KEY: ${ base64.Encode CLOUDFLARE_API_KEY}
