[env]
TALOSCONFIG = "{{config_root}}/provision/servonet/clusterconfig/talosconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"

_.file = ["{{config_root}}/.secrets.env"]

[tools]
"python" = "3.14.2"
"pipx:makejinja" = "2.8.2"
"aqua:budimanjojo/talhelper" = "3.1.3"
"aqua:casey/just" = "1.46.0"
"aqua:cilium/cilium-cli" = "0.19.0"
"aqua:cli/cli" = "2.86.0"
"aqua:cloudflare/cloudflared" = "2026.1.2"
"aqua:cue-lang/cue" = "0.15.4"
"aqua:FiloSottile/age" = "1.3.1"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:getsops/sops" = "3.11.0"
"aqua:helm/helm" = "4.1.0"
"aqua:helmfile/helmfile" = "1.2.3"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.7.1"
"aqua:kubernetes/kubernetes/kubectl" = "1.35.0"
"aqua:mikefarah/yq" = "4.50.1"
"aqua:siderolabs/talos" = "1.12.2"
"aqua:yannh/kubeconform" = "0.7.0"
"github:bitwarden/sdk" = "bws-v1.0.0"
"aqua:derailed/k9s" = "0.50.18"
