apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager/ks.yaml
  - ./cilium/ks.yaml
  - ./node-feature-discovery/ks.yaml
  # - nvidia-device-plugin/ks.yaml
  - ./external-secrets/ks.yaml
  - ./step-issuer/ks.yaml
