apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager/ks.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./metrics-server/ks.yaml
  - ./node-feature-discovery/ks.yaml
  # - nvidia-device-plugin/ks.yaml
  - ./reloader/ks.yaml
  - ./trust-manager/ks.yaml
  - ./tupper/ks.yaml
