---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
  namespace: external-secrets
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
      bitwardenServerSDKURL: https://bitwarden-sdk-server.kube-system.svc.servonet.lan:9998
      caProvider:
        type: ConfigMap
        name: bitwarden-ca-bundle
        key: ca.crt
        namespace: external-secrets
      organizationID: 9dbe5e66-6282-44f6-b1bb-b2b60034a341
      projectID: ca168f0e-9d7d-4dde-bd91-b2b60034a358
