---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
  namespace: external-secrets
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.servonet.lan:9998
      caProvider:
        type: ConfigMap
        name: bitwarden-ca-bundle
        key: ca.crt
        namespace: external-secrets
      organizationID: 9dbe5e66-6282-44f6-b1bb-b2b60034a341
      projectID: 15995f3f-b95d-4fcd-94bf-b3980160ab55
