---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: servonet-internal
spec:
  secretName: servonet-internal-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "${EXTERNAL_DOMAIN}"
  dnsNames:
    - "${EXTERNAL_DOMAIN}"
    - "*.${EXTERNAL_DOMAIN}"
