---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: servonet-external
spec:
  secretName: servonet-external-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "${EXTERNAL_DOMAIN}"
  dnsNames:
    - "${EXTERNAL_DOMAIN}"
    - "*.${EXTERNAL_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: servonet-internal
spec:
  secretName: servonet-internal-tls
  issuerRef:
    name: step
    kind: ClusterIssuer
  commonName: "servonet.lan"
  dnsNames:
    - "servonet.lan"
    - "echo.servonet.lan"
    - "prometheus.servonet.lan"
    - "rook.servonet.lan"
    - "grafana.servonet.lan"
    - "sabnzbd.servonet.lan"
    - "sonarr.servonet.lan"
    - "radarr.servonet.lan"
    - "jellyfin.servonet.lan"
