---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: servonet-internal
spec:
  secretName: servonet-internal-tls
  issuerRef:
    name: step
    kind: ClusterIssuer
  commonName: "servonet.lan"
  dnsNames:
    - "servonet.lan"
    - "echo.servonet.lan"
