---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-proxy
spec:
  jobLabel: envoy-proxy
  namespaceSelctors:
    matchNames:
      - networking
  podMetricsEndpoint:
    - port: metrics
      path: /stats/prometheus
      honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/component: proxy
      app.kubernetes.io/name: envoy
