---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./volumes.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  # - jellyfin/ks.yaml
