apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s.yaml
  - cilium.yaml
  - emqx.yaml
  - external-dns.yaml
  - grafana.yaml
  - jetstack.yaml
  - metrics-server.yaml
  - node-feature-discovery.yaml
  - nvidia-device-plugin.yaml
  - prometheus-community.yaml
  - rook-ceph.yaml
